# Generated by Django 5.2.7 on 2025-10-11 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload Excel files (.xlsx or .xls format only)', upload_to='excel_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Excel File',
                'verbose_name_plural': 'Excel Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
