# Generated by Django 5.0 on 2024-03-26 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Quantity', models.IntegerField()),
                ('Description', models.TextField()),
                ('ReleaseDate', models.DateField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('BrandName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brandmodel')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Body', models.TextField()),
                ('CreatedDate', models.DateField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='car.carmodel')),
            ],
        ),
    ]
